baseURL = 'https://codewithma.github.io/'
title = 'codewithma.github.io'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "My beautiful blog", Content = "Welcome to my blog!" }
  socialIcons = [
    { name = "github", url = "https://github.com/CodeWithMa" },
    { name = "codeberg", url = "https://codeberg.org/CodeWithMa" }
  ]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
